# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25010f21c0f9b5bb04ea8b003e2b1f93add1966c47867648f9af179f33eb2f966ff17eb263d8e96acadab95347c64ab742aab08e7ba43ecfae0de184d661a563

test:
  secret_key_base: 2cca358fc1a6c26c47a070c0fe2844bdc9a1dbe3df0a9838297086b81d44cf55399ac96597b31ff91b72d8814d56d396e5ce62b1d995a74e61ebca76a1f3ed1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
